# Copyright 2019 Wirepas Ltd
#
# Linux gateway
#

version: '3'
services:

    wm-sink:
        container_name: wm-sink
        image: ${IMAGE_NAME:-wirepas/gateway-x86:edge}
        build:
            context: ../..
            dockerfile: container/dev/Dockerfile
            args:
                DOCKER_BASE: ${DOCKER_BASE:-wirepas/base:1.1-ubuntu}
                IMAGE_NAME: ${IMAGE_NAME:-wirepas/gateway-x86:edge}
                VERSION: ${VERSION:-"local"}
                BUILD_DATE: ${BUILD_DATE}
                CROSS_BUILD_START_CMD: ${CROSS_BUILD_START_CMD}
                CROSS_BUILD_END_CMD: ${CROSS_BUILD_END_CMD}
                GIT_MANIFEST_FILE: ${GIT_MANIFEST_FILE}
                GIT_MANIFEST_URL: ${GIT_MANIFEST_URL}
                GIT_MANIFEST_BRANCH: ${GIT_MANIFEST_BRANCH}
                LXGW_C_MESH_API_HASH: ${LXGW_C_MESH_API_HASH}
                LXGW_SERVICES_HASH: ${LXGW_SERVICES_HASH}

        user: root
        privileged: true
        stdin_open: true
        tty: true

        restart: always
        env_file:
            - ../wm_gateway.env

        volumes:
            - /dev:/dev
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

        logging:
           driver: journald

        command: sink

    wm-transport:
        container_name: wm-transport
        image: wirepas/gateway-x86:edge

        user: root
        network_mode: host
        privileged: true
        stdin_open: true
        tty: true

        restart: always
        env_file:
            - ../wm_gateway.env

        volumes:
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
            # - ./my-tls-file:/etc/my-tls-file

        logging:
            driver: journald

        command: transport
