# Copyright 2019 Wirepas Ltd
#
# Linux gateway
#

version: '3'
services:

    wm-sink:
        container_name: wm-sink
        image: ${IMAGE_NAME:-wirepas/gateway-x86:latest}
        build:
            context: ../../..
            dockerfile: container/stable/Dockerfile
            args:
                IMAGE_NAME: ${IMAGE_NAME:-wirepas/gateway-x86:latest}
                VERSION: ${VERSION:-"1.2.0-rc.1"}
                BUILD_DATE: ${BUILD_DATE:-"undefined"}
                DOCKER_BASE: wirepas/base:1.1-ubuntu
                CROSS_BUILD_START_CMD: ":"
                CROSS_BUILD_END_CMD: ":"
                GIT_MANIFEST_FILE: ${GIT_MANIFEST_FILE:-gateway/stable.xml}
                GIT_MANIFEST_URL: ${GIT_MANIFEST_URL:-https://github.com/wirepas/manifest.git}
                GIT_MANIFEST_BRANCH: ${GIT_MANIFEST_BRANCH:-master}

        user: root
        privileged: true
        stdin_open: true
        tty: true

        restart: always
        env_file:
            - ../../wm_gateway.env

        volumes:
            - /dev:/dev
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

        logging:
           driver: journald

        command: sink

    wm-transport:
        container_name: wm-transport
        image: wirepas/gateway-x86

        user: root
        network_mode: host
        privileged: true
        stdin_open: true
        tty: true

        restart: always
        env_file:
            - ../../wm_gateway.env

        volumes:
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
            # - ./my-tls-file:/etc/my-tls-file

        logging:
            driver: journald

        command: transport
