name: build base runner for transport

on:
  push:
    branches:
      - master
      # TO BE REMOVED BEFORE MERGED
      - docker_base_runner
    paths:
      - '.github/workflows/docker_base_runner.yml'
      - 'docker/base_runner/Dockerfile'

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to push on docker hub'
        required: true

env:
  IMAGE_NAME: 'wirepas/gateway_base_runner'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: set tag for pushed changes
        if: github.event_name == 'push'
        # Hardcode tag to test for now
        run: echo '::set-env name=IMAGE_TAG::test'

      - name: set tag for manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: echo '::set-env name=IMAGE_TAG::${{ github.event.inputs.tag }}'

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/base_runner/Dockerfile
          platforms: linux/amd64,linux/arm
          build-args: PROTOBUF_VERSION=3.13.0
          push: true
          build-args: GATEWAY_BUILD_SHA1= ${{ github.sha }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
